### ISSUE TITLE
print() prints twice in Debug Console

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/debugpy#133]
## Environment data

-   VS Code version: 1.44.2
-   Extension version (available under the Extensions sidebar): 2020.3.71659
-   OS and version: Win 10, 1909
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): none
-   Relevant/affected Python-related VS Code extensions and their versions: none

## Expected behaviour

`print(2)` prints `2` in Debug Console

## Actual behaviour

`print(2)` prints `22` in Debug Console

## Steps to reproduce:

bug.py:
```
if True:
    print(1)
```

Set BP on print(1), Debug code, go to Debug Console, enter `print(2)`

**Comment by int19h** [comment]
This is a regression due to our fix for https://github.com/microsoft/ptvsd/issues/2036. The idea there was to allow print output caused by evals to appear in Debug Console even when "redirectOutput" is set to false (the default unless "internalConsole" is specified), by temporarily capturing output from those evals in-proc. But if "redirectOutput" is true, the adapter is also capturing stdout and stderr directly - and so we end up with doubled "output" events for the same thing.

**Comment by int19h** [comment]
This has been fixed.

**Comment by askamn** [comment]
Hi, not sure what was fixed, but I still see logs twice but only on windows. On Mac it's fine.

**Comment by bva99** [comment]
I still have this issue. Though I'm calling debugpy from vimspector (neovim).
@int19h Could you give me a tip on where to look for the bug?

**Comment by bva99** [comment]
Nevermind. After reading [this closed issue](https://github.com/microsoft/ptvsd/issues/2036#issuecomment-574129094) I added `"redirectOutput": false` to my `.vismpector.json` file and now everything is working correctly!
