### ISSUE TITLE
Texts in logpoint are being printed twice in the Debug Console when debugging cells 

### ISSUE THREAD

**Issue by luabud** [microsoft/debugpy#151]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. In a code cell, set up a breakpoint and right click on it, click on "edit breakpoint" and select "log message" in the drop down menu
2. Add a message and hit enter
3. Click on "debug cell" and open the Debug Console. Make sure you step over the line with the breakpoint and watch the output being printed twice

## Actual behavior
![image](https://user-images.githubusercontent.com/45497113/80657093-9cfecc80-8a37-11ea-990f-5a36b2118dad.png)

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.5.76036-dev
-   **VS Code version:** 1.44.2
-   **Python and/or Anaconda version:** Python 3.8.0 32 bit
-   **OS:** Windows
-   **Virtual environment:** venv

**Comment by int19h** [comment]
Might be related to https://github.com/microsoft/debugpy/issues/133

**Comment by ijoosong** [comment]
@int19h now that https://github.com/microsoft/debugpy/issues/133 was fixed, should this be closed?

**Comment by luabud** [comment]
This feature actually no longer exists, debugging is now supported in the native notebooks experience. Closing 😊

**Comment by rchiodo** [comment]
> This feature actually no longer exists, debugging is now supported in the native notebooks experience. Closing 😊

This feature still exists. Debugging in the interactive window is still supported.

**Comment by luabud** [comment]
Oh I confused it with the previous old notebook experience. However I can no longer reproduce the bug, can you?

**Comment by rchiodo** [comment]
No bug seems to not repro for me either. Trace point seems to only fire once.
