### ISSUE TITLE
Python subprocess returns unknown option --module when debugging if 'subProcess: true' in launch.json

### ISSUE THREAD

**Issue by pbesson-invn** [microsoft/debugpy#533]
## Environment data

-   VS Code version: 1.52.1 
-   Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS and version: Win10 (Windows_NT ia32 10.0.16299)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: PyLance

```
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:50.160Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT ia32 10.0.16299
```

## Expected behaviour

When debugging a python script, it should be able to execute `subprocess.run([sys.executable, '-m', 'foo'])` successfully (assuming `foo` module exists).

## Actual behaviour

When `"subProcess": true` is present in launch.json and when debugging a python script that calls `subprocess.run([sys.executable, '-m', 'foo'])`,  it fails with the error: 

```
$  /usr/bin/env c:\\Workspace\\bug_subprocess\\venv\\Scripts\\python.exe c:\\Users\\XXX\\.vscode\\extensions\\ms-python.python-2021.1.502429796\\pythonFiles\\lib\\python\\debugpy\\launcher 509
71 -- c:\\Workspace\\bug_subprocess\\run.py
unknown option --module
usage: c:\Workspace\bug_subprocess\venv\Scripts\python.exe [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
```

Calling script directly from a terminal works as expected.

## Steps to reproduce:

1. Create file `foo.py` containing:

```
print('hello from foo')
```

2. Create file `run.py` containing:

```
import subprocess
import sys
subprocess.run(args=[sys.executable, '-u'] + ['-m', 'foo'])
```

3. Create `launch.json` file containing:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "subProcess": true
        }
    ]
}
```

4. Debug `run.py`

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
User belongs to experiment group 'AlwaysDisplayTestExplorer - control'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonInstallPylintButtonFirstcf'
> conda --version
> pyenv root
> python3.7 c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2021-01-25 17:39:14: Detection of Python Interpreter for Command py and args -3.6 failed as file Python 3.6 not found!

 -3.7-64
 -3.7-32
 -2.7-64 does not exist
> pyenv root
> pyenv root
Error 2021-01-25 17:39:15: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'c:\Workspace\bug_subprocess\.vscode\settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\Workspace\bug_subprocess\.vscode\settings.json')
	at _handleError (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:745:473)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:9:344778)
	at async p.doesFileNeedToBeFixed (c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:59:500280)
	at async c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:59:499407
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:59:499353)
	at async p.updateTestSettings (c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:59:498980)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Python interpreter path: .\venv\Scripts\python.exe
Starting Pylance language server.
> pyenv root
> pyenv root
> c:\Workspace\bug_subprocess\venv\Scripts\python.exe c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Workspace\bug_subprocess\run.py
cwd: c:\Workspace\bug_subprocess
> c:\Workspace\bug_subprocess\venv\Scripts\python.exe c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Workspace\bug_subprocess\run.py
cwd: c:\Workspace\bug_subprocess
> conda --version
> pyenv root
> pyenv root
> c:\Workspace\bug_subprocess\venv\Scripts\python.exe c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import pylint"
> c:\Workspace\bug_subprocess\venv\Scripts\python.exe c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import pylint"
> c:\Workspace\bug_subprocess\venv\Scripts\python.exe c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import pylint"
> c:\Workspace\bug_subprocess\venv\Scripts\python.exe c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import pylint"

Linter 'pylint' is not installed. Please install it or select another linter".
Error: Module 'pylint' not installed.
> c:\Workspace\bug_subprocess\venv\Scripts\python.exe c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Workspace\bug_subprocess\foo.py
cwd: c:\Workspace\bug_subprocess
> c:\Workspace\bug_subprocess\venv\Scripts\python.exe c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Workspace\bug_subprocess\foo.py
cwd: c:\Workspace\bug_subprocess
> c:\Workspace\bug_subprocess\venv\Scripts\python.exe c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import pylint"
> c:\Workspace\bug_subprocess\venv\Scripts\python.exe c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import pylint"
> c:\Workspace\bug_subprocess\venv\Scripts\python.exe c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import pylint"
> c:\Workspace\bug_subprocess\venv\Scripts\python.exe c:\Users\xxx\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\pyvsc-run-isolated.py -c "import pylint"

Linter 'pylint' is not installed. Please install it or select another linter".
Error: Module 'pylint' not installed.
```

</p>
</details>

## Extensions debug files

* [debugger.vscode_be2ef4e6-e319-41bb-8ec9-1ee926fe551d.log](https://github.com/microsoft/debugpy/files/6317924/debugger.vscode_be2ef4e6-e319-41bb-8ec9-1ee926fe551d.log)
* [debugpy.adapter-15832.log](https://github.com/microsoft/debugpy/files/6317925/debugpy.adapter-15832.log)
* [debugpy.launcher-13744.log](https://github.com/microsoft/debugpy/files/6317926/debugpy.launcher-13744.log)
* [debugpy.pydevd.2168.log](https://github.com/microsoft/debugpy/files/6317927/debugpy.pydevd.2168.log)
* [debugpy.server-2168.log](https://github.com/microsoft/debugpy/files/6317928/debugpy.server-2168.log)

**Comment by fabioz** [comment]
There were some of improvements in the monkey-patching in the meanwhile, so, I think that this may have been fixed already (and I couldn't reproduce it here).

@pbesson-invn can you check if it's working for you in the latest version of the debugger and report back?

**Comment by romain-intel** [comment]
I ran into the same issue and can confirm that I can reproduce the simple test case above. I believe I have everything up-to-date. My information is as follows:

 - VS Code version: 1.55.2
 - Extension version (available under the Extensions sidebar): v2021.3.680753044
 - OS and version: MacOS 11.2.3 but also ran remotely on Ubuntu
 - Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.7.1 but also ran on linux 3.7.10
 - Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda and none remotely
 - Relevant/affected Python packages and their versions: N/A
 - Relevant/affected Python-related VS Code extensions and their versions: N/A
 - Value of the python.languageServer setting: PyLance

The same thing happens and I get the following error message: 
```
cd /Users/XXX/Documents/RemoteRepos/Dev/data-pipelines ; /usr/bin/env /Users/XXX/miniconda3/bin/python /Users/XXX/.vscode/extensions/ms-python.python-2021.3.680753044/pythonFiles/lib/python/debugpy/launcher 52321 -- /Users/XXX/Documents/RemoteRepos/Dev/data-pipelines/.vscode/run.py 
unknown option --module
usage: /Users/XXX/miniconda3/bin/python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
```

Let me know if you need additional information.

**Comment by pbesson-invn** [comment]
@fabioz I still have the bug with ms-python.python extension version v2021.3.680753044 and vscode 1.55.1

* Version: 1.55.1 (system setup)
* Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
* Date: 2021-04-07T15:01:54.977Z
* Electron: 11.3.0
* Chrome: 87.0.4280.141
* Node.js: 12.18.3
* V8: 8.7.220.31-electron.0
* OS: Windows_NT ia32 10.0.16299

**Comment by fabioz** [comment]
Thanks for the feedback. I still couldn't reproduce it locally, so, I still don't know what's wrong.

Can you provide the logging output when you get that error?

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by pbesson-invn** [comment]
@fabioz I have attach debug files to the opening comment https://github.com/microsoft/debugpy/issues/533#issue-793632931 per your request.

**Comment by fabioz** [comment]
Thanks for the logs, I think I found the issue.... I'm not sure when a release with this fix can be made, but it's a pretty small change (https://github.com/microsoft/debugpy/pull/589), so, maybe you can manually apply those changes locally.

To know where that file is located you can execute:

```
from _pydev_bundle import pydev_monkey
print(pydev_monkey.__file__)
```

**Comment by pbesson-invn** [comment]
I have tried your patch locally and it is now working 👍 

Thank you for taking a look and fixing this !
