### ISSUE TITLE
Support Python 3.11 frozen modules

### ISSUE THREAD

**Issue by fabioz** [microsoft/debugpy#861]
See: https://github.com/fabioz/PyDev.Debugger/issues/213

**Comment by YvesDup** [comment]
May be this issue can be reopen ? 
https://github.com/Microsoft/vscode-python/issues/941

**Comment by int19h** [comment]
@YvesDup You should create an issue in the corresponding repository - this one is specifically for debugpy, but the issue you've linked to is about the way vscode-python *uses* debugpy.

**Comment by gvanrossum** [comment]
A workaround is to add this to the configuation in launch.json:
```
"pythonArgs": ["-Xfrozen_modules=off"],
```

**Comment by YvesDup** [comment]
@int19h Sorry :( for the misunderstood. I just proposed to add a new entriy to pass args to Python like proposed in that issue. But it already exists as the "pythonArgs" of lauch.json.

I am wondering what are the differences debugpy and pydev.debugger ? Are they both a debugger for Python or not or something more ? Thank

**Comment by int19h** [comment]
PyDev.Debugger aka pydevd is one of the oldest Python debuggers around - it's the one originally made for Eclipse/PyDev, hence the name. It implements core functionality such as stepping and breakpoints. It runs inside the process being debugged, and thus, in general, it does things that are best done *from within* that process.

debugpy is basically a wrapper around pydevd that adds process lifetime management. It runs as a separate process from the debuggee, and thus, in general, it does things that are best done *from outside* of the process that is being debugged. So it can handle requests to launch processes for debugging or attach to running processes (and sets up pydevd as needed to handle those scenarios), and it keeps track of and coordinates processes in a multiprocess debug session. But it also does stuff such as stdout/stderr output capture.

To allow for easy deployment, debugpy vendors (i.e. embeds) all of its dependencies outside of the Python stdlib, including pydevd. So you don't have to worry about any of this while using it, but when we track work to be done, it can end up in either repo depending on where it was originally reported, and what the issue is.

**Comment by int19h** [comment]
Fixed by https://github.com/microsoft/debugpy/pull/937

**Comment by dc-avasilev** [comment]
not fixed https://github.com/microsoft/debugpy/pull/937/files#r1145404312

**Comment by ergoithz** [comment]
related: https://github.com/python/cpython/issues/106723
